variable "aws_region" {
  description = "AWS region to deploy resources into."
  type        = string
}

variable "aws_account_id" {
  description = "AWS account ID where the IAM role will be created."
  type        = string
}

variable "s3_bucket_name" {
  description = "Name of the S3 bucket for raw data."
  type        = string
}

variable "bucket_prefix" {
  description = "Folder/prefix inside the S3 bucket for Databricks access."
  type        = string
  default     = "police"
}

variable "iam_role_name" {
  description = "Name of the IAM role Databricks will assume."
  type        = string
}

variable "databricks_storage_credential_name" {
  description = "Name of the Databricks Unity Catalog storage credential."
  type        = string
}

variable "databricks_external_location_name" {
  description = "Name of the Databricks Unity Catalog external location."
  type        = string
}

variable "databricks_principal" {
  description = "Databricks user/group/service principal to grant on the external location."
  type        = string
}

variable "databricks_uc_master_role_arn" {
  description = "Databricks Unity Catalog master role ARN for AWS."
  type        = string
}

variable "bootstrap_external_id" {
  description = "Temporary external ID used during bootstrap stage."
  type        = string
  default     = "0000"
}

variable "databricks_external_id" {
  description = "Real external ID generated by Databricks storage credential."
  type        = string
  default     = ""
}

variable "create_external_location" {
  description = "Whether to create the external location in this apply."
  type        = bool
  default     = false
}